# Generated by Django 2.2.15 on 2020-08-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bluehost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerId', models.CharField(max_length=200)),
                ('ProductName', models.CharField(choices=[('', ''), ('domain', 'Domain'), ('hosting', 'Hosting'), ('email', 'Email'), ('pdomain', 'P-Domain'), ('edomain', 'E-Domain')], max_length=7)),
                ('Domain', models.CharField(max_length=200)),
                ('StartDate', models.DateTimeField(auto_now_add=True)),
                ('DurationMonths', models.IntegerField()),
            ],
        ),
    ]
