# Generated by Django 2.2.15 on 2020-08-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluehost', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bluehost',
            new_name='Product',
        ),
    ]
